# Generated by Django 4.1.1 on 2022-10-13 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burt', '0003_helpermodel_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempDataHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.TextField()),
                ('main_keywords', models.TextField()),
            ],
        ),
    ]
